### PR TITLE
add script to resize boot volumes on compute nodes

### PR DESCRIPTION
**Pull request by andriy-safe-ai**
Tested on a dev cluster. The script took about an hour to run on a 32 node cluster. Might take slightly longer on production since our compute nodes take about 10 minutes to fully restart.

### CODE REVIEW

**Comment by steven-basart** [comment]
You have any tests for this? I can read mumbo jumbo

**Comment by andriy-safe-ai** [comment]
@steven-basart 

On dev cluster:
Before running the script
```
$ ssh compute-permanent-node-37
$ df -H
Filesystem              Size  Used Avail Use% Mounted on
.....
/dev/sda3                45G   22G   24G  49% /
.....
```

After running the script
```
$ ssh compute-permanent-node-37
$ df -H
....
/dev/sda3                99G   22G   77G  23% /
....
```

Same for all nodes.

**Comment by andriy-safe-ai** [comment]
Testing:
```
# Check the resized boot volume size
sudo sinfo -S "%n" -o "%n" | tail -n +2 > host_file
pdsh -w ^host_file 'df -H | grep /dev/sda3'
```

Output:
```
compute-permanent-node-588: /dev/sda3                99G   22G   77G  23% /
compute-permanent-node-674: /dev/sda3                99G   22G   77G  23% /
compute-permanent-node-692: /dev/sda3                99G   22G   77G  23% /
compute-permanent-node-818: /dev/sda3                99G   22G   77G  23% /
compute-permanent-node-431: /dev/sda3                99G   22G   77G  23% /
compute-permanent-node-123: /dev/sda3                99G   22G   77G  23% /
```

**Review by trent-safe-ai — COMMENTED** [review]
@andriy-safe-ai there doesn't seem to be any context for these files? Can you please add a summary and put all the info/code into one file?

**Pull request merged**
