### PR TITLE
Adds opengl/mesa to cais-compute ansible role

### PR DESCRIPTION
**Pull request by andriy-safe-ai**
Ran `ansible-playbook cais_*` to install packages.

Ran the following ansible playbook to make sure that packages are present on all compute nodes:
```
---

- name: Check if package is installed
  hosts: compute
  become: true
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
#    - name: Print the package facts
#      ansible.builtin.debug:
#        var: ansible_facts.packages
    - name: Check whether the package mesa-libOSMesa  is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['mesa-libOSMesa'] | length }} versions of mesa-libOSMesa are installed!"
      when: "'mesa-libOSMesa' in ansible_facts.packages"
    - name: Check whether the package mesa-libOSMesa-devel is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['mesa-libOSMesa-devel'] | length }} versions of mesa-libOSMesa-devel are installed!"
      when: "'mesa-libOSMesa-devel' in ansible_facts.packages"
    - name: Check whether the package glfw is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['glfw'] | length }} versions of glfw are installed!"
      when: "'glfw' in ansible_facts.packages"
    - name: Check whether the package glfw-devel is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['glfw-devel'] | length }} versions of glfw-devel are installed!"
      when: "'glfw-devel' in ansible_facts.packages"
    - name: Check whether the package mesa-libGL is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['mesa-libGL'] | length }} versions of mesa-libGL are installed!"
      when: "'mesa-libGL' in ansible_facts.packages"
    - name: Check whether the package mesa-libGL-devel is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['mesa-libGL-devel'] | length }} versions of mesa-libGL-devel are installed!"
      when: "'mesa-libGL-devel' in ansible_facts.packages"
```

Results("ok" means that the packages are present): 
```
PLAY RECAP ************************************************************************************************************************************************************************
inst-1izto-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-3lkhl-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-4550h-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-4aqno-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-7vnv6-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-aa2un-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-bmccd-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-cpqls-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-e6vvd-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-encjw-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-evoyb-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-fnbev-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-fwhck-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-gp7wn-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-hgqwx-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-hsfgo-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-mdqbh-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-necvh-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-nfanw-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-qj9qc-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-rbxtc-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-rk4hy-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-u90mk-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-ul7as-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-umizk-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-unr7l-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-vjaro-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-wzlds-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-xydnk-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-yajr3-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-ysctj-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
inst-yum8n-watch-tower     : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

### CODE REVIEW

**Comment by steven-basart** [comment]
Fix the commit message to make it declarative then it looks good to me.  I changed the title as such if you wanted to see the example.

**Comment by andriy-safe-ai** [comment]
@steven-basart 

Why Declarative? What's wrong with imperative?

Even official Git documentation recommends imperative: https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages

**Comment by steven-basart** [comment]
It's the style "I grew up with" at Google.  Meant to be read as "this commit adds blah."

**Comment by andriy-safe-ai** [comment]
Updated commit message.

**Review by steven-basart — APPROVED** [review]
LGTM

**Pull request merged**
