### PR TITLE
remove devtoolset-5 from cais compute playbook

### PR DESCRIPTION
**Pull request by andriy-safe-ai**
Removed the play that installs `devtoolset-5`.

### CODE REVIEW

**Comment by steven-basart** [comment]
We also need to uninstall it on prod because it is installed.

**Review by steven-basart — CHANGES_REQUESTED** [review]
Show it's been deleted on prod before merging. Otherwise dev will be out of sync with prod.

**Comment by andriy-safe-ai** [comment]
@steven-basart 

I didn't manually remove from prod. If the cais compute playbook has been modified it wasn't a change that I made.

**Comment by andriy-safe-ai** [comment]
I wrote a short Ansible Playbook to check whether dev toolset-5 is installed on any of our nodes:

---

- name: Check if devtoolset-5 is installed
  hosts: login,bastion,slurm_backup,compute
  become: true
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Check whether a package called devtoolset-5 is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['devtoolset-5'] | length }} versions of devtoolset are installed!"
      when: "'devtoolset-5' in ansible_facts.packages"
Basically, the second play will execute if we have dev toolset-5 installed otherwise it is skipped.

Cropped output:

TASK [Check whether a package called devtoolset-5 is installed] **********************************************************
skipping: [watch-tower-login]
skipping: [watch-tower-bastion]
skipping: [watch-tower-backup]
skipping: [inst-umizk-watch-tower]
skipping: [inst-ul7as-watch-tower]
skipping: [inst-aa2un-watch-tower]
skipping: [inst-encjw-watch-tower]
skipping: [inst-ysctj-watch-tower]
skipping: [inst-unr7l-watch-tower]
skipping: [inst-fwhck-watch-tower]
skipping: [inst-qj9qc-watch-tower]
skipping: [inst-gp7wn-watch-tower]
skipping: [inst-4550h-watch-tower]
skipping: [inst-xydnk-watch-tower]
skipping: [inst-hgqwx-watch-tower]
skipping: [inst-vjaro-watch-tower]
skipping: [inst-rk4hy-watch-tower]
skipping: [inst-4aqno-watch-tower]
skipping: [inst-evoyb-watch-tower]
skipping: [inst-rbxtc-watch-tower]
skipping: [inst-fnbev-watch-tower]
skipping: [inst-wzlds-watch-tower]
skipping: [inst-7vnv6-watch-tower]
skipping: [inst-yum8n-watch-tower]
skipping: [inst-yajr3-watch-tower]
skipping: [inst-u90mk-watch-tower]
skipping: [inst-nfanw-watch-tower]
skipping: [inst-3lkhl-watch-tower]
skipping: [inst-mdqbh-watch-tower]
skipping: [inst-e6vvd-watch-tower]
skipping: [inst-hsfgo-watch-tower]
skipping: [inst-1izto-watch-tower]
skipping: [inst-necvh-watch-tower]
skipping: [inst-bmccd-watch-tower]
devtoolset-5 is not installed on any of our nodes.

**Comment by andriy-safe-ai** [comment]
@steven-basart

**Review by steven-basart — APPROVED** [review]

**Comment by steven-basart** [comment]
LGTM

**Pull request merged**
